In [2]:
# Lets import allthe necessary libraries
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [3]:
# Lets use pandas to read the "email.csv" file
df = pd.read_csv('spam_ham_dataset.csv')

In [4]:
# Lets print the first 5 rows
df.head()

,Unnamed: 0,label,text,label_num
0,605,ham,Subject: enron methanol ; meter # : 988291\r\n...,0
1,2349,ham,"Subject: hpl nom for january 9 , 2001\r\n( see...",0
2,3624,ham,"Subject: neon retreat\r\nho ho ho , we ' re ar...",0
3,4685,spam,"Subject: photoshop , windows , office . cheap ...",1
4,2030,ham,Subject: re : indian springs\r\nthis deal is t...,0

We can clearly see that the columns are the individual words, which in total are 3002 in numbers

In [5]:
df = pd.DataFrame(df)

# Lets read the values of "label" column
df.label_num.value_counts()
# Here, 0 means "Ham", and 1 means "Spam"

0    3672
1    1499
Name: label_num, dtype: int64

In [6]:
df.shape

(5171, 4)

In [7]:
# Lets  drop the column "Unnamed: 0" as it has no useful data
df = df.drop(['Unnamed: 0'],axis = 1)

In [8]:
# Printing the first five rows of the updataed dataframe
df.head()

  label                                               text  label_num
0   ham  Subject: enron methanol ; meter # : 988291\r\n...          0
1   ham  Subject: hpl nom for january 9 , 2001\r\n( see...          0
2   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...          0
3  spam  Subject: photoshop , windows , office . cheap ...          1
4   ham  Subject: re : indian springs\r\nthis deal is t...          0

In [9]:
# lets detect and remove duplicate emails, if there are any
df.drop_duplicates(inplace = True)
df.shape

(4993, 3)

We can see that the shape of the dataframe has reduced, because there were duplicate emails, and they are now removed

In [10]:
# lets check if there are any null data in all columns
df.isnull().sum()

label        0
text         0
label_num    0
dtype: int64

In [11]:
# Now, lets develop X, that consists of all emails and a y, that consists of out label_num
X = df['text']
y = df.label_num

In [57]:
X

0       Subject: enron methanol ; meter # : 988291\r\n...
1       Subject: hpl nom for january 9 , 2001\r\n( see...
2       Subject: neon retreat\r\nho ho ho , we ' re ar...
3       Subject: photoshop , windows , office . cheap ...
4       Subject: re : indian springs\r\nthis deal is t...
                              ...
5165    Subject: fw : crosstex energy , driscoll ranch...
5166    Subject: put the 10 on the ft\r\nthe transport...
5167    Subject: 3 / 4 / 2000 and following noms\r\nhp...
5169    Subject: industrial worksheets for august 2000...
5170    Subject: important online banking alert\r\ndea...
Name: text, Length: 4993, dtype: object

# Let's represent text as numerical data

We will use CountVectorizer to "convert text into a matrix of token counts"

In [13]:
# import and instantiate CountVectorizer (with the default parameters)
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()

In [14]:
# Let's learn the vocabulary from X
count_vect.fit(X)

CountVectorizer()

In [15]:
# Lets examine the fitted vocabulaty
count_vect.get_feature_names()

['00',
 '000',
 '0000',
 '000000',
 '000000000002858',
 '000000000049773',
 '000080',
 '000099',
 '0001',
 '00018',
 '00020608',
 '0004',
 '0005',
 '0008',
 '001',
 '0010',
 '001001',
 '0012',
 '001452',
 '002',
 '0022',
 '00221',
 '0025',
 '0027',
 '0028',
 '0029',
 '00298',
 '003',
 '0030',
 '003002',
 '0031',
 '0033',
 '0038',
 '004',
 '0042',
 '0043',
 '0044',
 '0045',
 '0046',
 '0047',
 '0049',
 '005',
 '00501723',
 '0051',
 '00534580',
 '006',
 '006600',
 '0067',
 '007',
 '0071',
 '0074',
 '008',
 '0080',
 '0085201238',
 '009',
 '0090',
 '01',
 '010',
 '0100',
 '0101',
 '011',
 '0117',
 '012',
 '012603',
 '013',
 '0130',
 '014',
 '01405',
 '01408304990',
 '01474',
 '015',
 '016',
 '017',
 '0170',
 '01778',
 '0182',
 '0184',
 '019',
 '019017',
 '01915',
 '02',
 '020',
 '0200',
 '02010207',
 '021',
 '022',
 '0232',
 '024',
 '025',
 '0255',
 '025648',
 '026',
 '027',
 '028',
 '02886',
 '02897893',
 '029',
 '03',
 '030',
 '0300',
 '03090806',
 '031',
 '0310041',
 '03149',
 '032',
 '0324',
 '0325567',
 '033',
 '0331',
 '034',
 '0347',
 '035',
 '0357',
 '036',
 '0361770',
 '0363',
 '036474336',
 '037',
 '0373',
 '0375',
 '038',
 '0380',
 '039',
 '0393',
 '0398',
 '04',
 '040',
 '0400',
 '04005',
 '0401',
 '041',
 '0413',
 '0416',
 '042',
 '0424040',
 '043',
 '0432',
 '0435',
 '0439',
 '044',
 '045',
 '046',
 '04604902',
 '04607001',
 '0469',
 '048',
 '0488',
 '049',
 '0491',
 '05',
 '050',
 '0500',
 '0505',
 '0506',
 '0507544',
 '052',
 '053',
 '054',
 '0542',
 '055',
 '056',
 '0569',
 '0570',
 '0573',
 '058',
 '0584',
 '059',
 '0598',
 '06',
 '060',
 '0600',
 '061',
 '061300',
 '06142000',
 '0614842809561657',
 '062',
 '062000',
 '0630',
 '064',
 '065',
 '066',
 '067',
 '068',
 '0680',
 '0688',
 '069',
 '07',
 '070',
 '0700',
 '07080',
 '071',
 '0713',
 '072',
 '073',
 '075',
 '076',
 '078',
 '0788',
 '08',
 '080',
 '0800',
 '081',
 '082',
 '0825',
 '083',
 '0839',
 '084',
 '085',
 '087',
 '088',
 '0880',
 '088889774',
 '089',
 '0891',
 '09',
 '0900',
 '09050804',
 '0910',
 '09110129',
 '092',
 '0920',
 '09216',
 '093',
 '094',
 '0945',
 '095',
 '0952',
 '096',
 '0972',
 '0973',
 '0977',
 '098',
 '0980308',
 '0980391',
 '0980438',
 '0980439',
 '0980694',
 '0980803',
 '0980805',
 '0980877',
 '0984126',
 '0984132',
 '0984136',
 '0984179',
 '0984229',
 '0984273',
 '0984284',
 '0984654',
 '0985192',
 '0986315',
 '0986363',
 '0986511',
 '0986563',
 '0986725',
 '0986757',
 '0986892',
 '0987283',
 '0988743',
 '0988746',
 '0989703',
 '0989708',
 '0989709',
 '0989740',
 '0989751',
 '0989813',
 '0989814',
 '0989842',
 '0991',
 '10',
 '100',
 '1000',
 '10000',
 '1001',
 '10010000873445724',
 '10010000876293700',
 '100145',
 '1002',
 '1005',
 '1007',
 '10077',
 '100896',
 '101',
 '1010',
 '10103',
 '1012',
 '10126',
 '101473',
 '101522',
 '101530',
 '101574',
 '1019',
 '101985',
 '102',
 '102056072',
 '1023',
 '102372',
 '1024',
 '102420',
 '1026',
 '102775',
 '10290',
 '103',
 '1031',
 '103143',
 '103745',
 '1038590',
 '1038591',
 '104',
 '1040',
 '104001',
 '104210',
 '104256',
 '104285',
 '1043',
 '104301',
 '104323',
 '104353',
 '104354',
 '104355',
 '104382',
 '1044',
 '1046043196122050333',
 '104738',
 '104940',
 '104975',
 '105',
 '1050',
 '10500',
 '10502',
 '105124',
 '1052',
 '10545',
 '1055',
 '105629',
 '105630',
 '105631',
 '105632',
 '105633',
 '105634',
 '105638',
 '106',
 '1060',
 '1061',
 '1062',
 '106269',
 '106290',
 '106292',
 '1063',
 '106736',
 '1068',
 '107',
 '1071',
 '1072',
 '107937',
 '108',
 '1080',
 '108058',
 '108146',
 '108246',
 '1084',
 '1085609',
 '108564',
 '1086002',
 '108672',
 '1087',
 '1089',
 '109',
 '1090',
 '109046',
 '10939',
 '109475',
 '1095',
 '10955',
 '109660',
 '109670',
 '1098',
 '1099',
 '109925',
 '11',
 '110',
 '1100',
 '11000',
 '1102',
 '1103',
 '1104',
 '1105',
 '110502',
 '1106',
 '11079',
 '111',
 '111111',
 '1113',
 '112',
 '1123',
 '11230',
 '113',
 '1130',
 '113050',
 '1132',
 '1135',
 '1136',
 '1137',
 '113858',
 '1139',
 '114',
 '11400',
 '114096',
 '114099',
 '11417',
 '114427',
 '1145',
 '114514',
 '11464992',
 '1147',
 '115',
 '1150',
 '11500',
 '1151',
 '115101',
 '1155',
 '1156',
 '1157',
 '116',
 '1160',
 '1163',
 '1164',
 '1165',
 '11669',
 '1168',
 '117',
 '1171',
 '1174',
 '11743',
 '117848',
 '1179',
 '118',
 '1180',
 '1181',
 '11814',
 '118532',
 '11864',
 '11871528',
 '1188',
 '1189',
 '119',
 '119068',
 '1191',
 '1191626',
 '11958',
 '1199',
 '12',
 '120',
 '1200',
 '12000',
 '120000',
 '1201',
 '120266',
 '120359',
 '1206478',
 '1207',
 '12079',
 '120866',
 '120891',
 '121',
 '1210',
 '1212',
 '122',
 '12200',
 '12214',
 '122218',
 '1225',
 '1226030',
 '12278',
 '123',
 '1233',
 '123395',
 '1234',
 '123456',
 '1237',
 '1238',
 '1239190',
 '124',
 '124400',
 '1248',
 '124972',
 '125',
 '1250',
 '12500',
 '125066',
 '1252',
 '1256',
 '125783',
 '125786',
 '125807',
 '125822',
 '125827',
 '125828',
 '125836',
 '125895',
 '125899',
 '125900',
 '126',
 '1260',
 '126166',
 '126270',
 '126281',
 '126289',
 '126336',
 '126351',
 '126355',
 '126358',
 '126360',
 '126365',
 '126370',
 '1265',
 '1266',
 '12667',
 '1269',
 '127',
 '1270',
 '1274',
 '127445',
 '1275',
 '12780',
 '12782',
 '127856',
 '128',
 '1280',
 '128285',
 '12831939',
 '1283944723085771570',
 '1286',
 '128952',
 '129',
 '1290',
 '12930',
 '1294',
 '12945',
 '1295',
 '129706',
 '13',
 '130',
 '1300',
 '13000',
 '13035',
 '130880',
 '130913',
 '130917',
 '131',
 '131048',
 '131054',
 '1314',
 '1315',
 '131720',
 '131729',
 '132',
 '132030',
 '1326',
 '1328',
 '132832',
 '132845',
 '132975',
 '132976',
 '133',
 '133010',
 '133088',
 '133125',
 '133168',
 '133169',
 '133173',
 '133179',
 '133196',
 '1332',
 '133219',
 '133255',
 '133257',
 '133259',
 '133291',
 '1333',
 '133304',
 '133308',
 '133342',
 '133344',
 '1334',
 '133435',
 '1335',
 '1336',
 '134',
 '1342',
 '1343',
 '1344',
 '134755',
 '134987',
 '135',
 '1350',
 '1351',
 '1354',
 '135664',
 '135708',
 '135714',
 '135842',
 '135895',
 '135931652',
 '135958',
 '136',
 '1360',
 '1361',
 '136185',
 '136222',
 '136225',
 '136286',
 '136287',
 '136744',
 '136880',
 '136933',
 '137',
 '1370',
 '137156',
 '1372',
 '137205',
 '1373',
 '13746',
 '1375',
 '137595',
 '1376',
 '137858',
 '137868',
 '137870',
 '137971',
 '138',
 '138017',
 '138023',
 '138033',
 '138049',
 '138086',
 '138094',
 '138095',
 '1381',
 '138103',
 '138233',
 '138332',
 '138342',
 '138359',
 '1384',
 '138536',
 '138544',
 '138546',
 '138550',
 '138553',
 '138554',
 '138570',
 '138572',
 '138578',
 '1386',
 '138601',
 '138605',
 '138628',
 '138658',
 '138661',
 '138662',
 '138665',
 '138800',
 '138822',
 '138841',
 '138848',
 '138856',
 '139',
 '1390',
 '139055',
 '139057',
 '139058',
 '139066',
 '139067',
 '139068',
 '1391',
 '1392',
 '139363',
 '139397',
 '1394',
 '13964',
 '139661',
 '139671',
 '139674',
 '1399',
 '14',
 '140',
 '1400',
 '1401',
 '14031399',
 '140327',
 '140330',
 '140332',
 '140334',
 '140336',
 '140337',
 '14051',
 '14086',
 '1409',
 '140991',
 '141',
 '1411',
 '141186',
 '1416',
 '141691',
 '1418',
 '141833',
 '141877',
 '141883',
 '141884',
 '141977',
 '142',
 '142002',
 '142035',
 '142036',
 '142037',
 '14226',
 '142509',
 '1427',
 '1428',
 '1429',
 '143',
 '14300',
 '1431',
 '1434',
 '143558',
 '143559',
 '1436',
 '143673',
 '143709',
 '1438',
 '143885',
 '143887',
 '143974',
 '144',
 '144049',
 '144052',
 '1441',
 '1442',
 '144264',
 '144271',
 '1447',
 '144917',
 '144932',
 '144936',
 '145',
 '1450',
 '145075',
 '145125',
 '1454',
 '1458',
 '145833',
 '1459',
 '146',
 '1460',
 '1462',
 '1465',
 '14689',
 '146907159',
 '147',
 '147092',
 '1472',
 '1474',
 '147866',
 '148',
 '1481',
 '148376',
 '148381',
 '148382',
 '148384',
 '148386',
 '148388',
 '148390',
 '148391',
 '148396',
 '148415904',
 '1485',
 '1487',
 '1488',
 '14886',
 '1489',
 '148923',
 '149',
 '1491',
 '149421',
 '1495',
 '1497',
 '15',
 '150',
 '1500',
 '15000',
 '150325',
 '1505',
 '1506',
 '150642',
 '1508',
 '151',
 '1512',
 '151203',
 '1516',
 '151666',
 '151669',
 '151694',
 '1517',
 '152',
 '1520',
 '1521',
 '1524',
 '1525',
 '152638',
 '1528',
 '153',
 '1530',
 '1534',
 '153864',
 '154',
 '1543',
 '154608',
 '1547',
 '1549',
 '155',
 '1550',
 '15500',
 '155118',
 '1552',
 '1553',
 '1554',
 '1558',
 '156',
 '1560',
 '15600',
 '156071',
 '156247',
 '156256',
 '156258',
 '156292',
 '1563',
 '15631',
 '156337',
 '156342',
 '156383',
 '156387',
 '156657',
 '156658',
 '1567',
 '1568',
 '157',
 '157006',
 '15718',
 '157233',
 '157278',
 '157279',
 '157284',
 '157288',
 '157564',
 '157572',
 '1576',
 '158',
 '1581',
 '158220',
 '158625',
 '15867384',
 '1587',
 '15880647714247442333',
 '159',
 '1591',
 '159194',
 '1594',
 '1595',
 '1596',
 '159640',
 '15975',
 '1598',
 '16',
 '160',
 '1600',
 '1601',
 '1603',
 '160579',
 '1606',
 '161',
 '16100',
 '161541',
 '1618',
 '162',
 '16231',
 '16259',
 '16275',
 '16276',
 '1628',
 '163',
 '163005',
 '16323',
 '16358',
 '1638',
 '163815',
 '163874',
 '164',
 '164003',
 '164172',
 '1646',
 '164669',
 '164708',
 '16488',
 '16495',
 '165',
 '165331',
 '165373',
 '1658245',
 '166',
 '1660',
 '166026',
 '1663800',
 '166395',
 '166459',
 '166523',
 '1667',
 '166817',
 '166853',
 '166888',
 '166989',
 '167',
 '1670',
 '1671',
 '168',
 '1682426017',
 '1683',
 '16840862',
 '168454',
 '168509',
 '16884',
 '16888',
 '168884',
 '1689',
 '169',
 '169301',
 '1694',
 '169625',
 '17',
 '170',
 '1700',
 '170133',
 '17054701',
 '1707',
 '17097613',
 '171',
 '1714',
 '1717',
 '1718',
 '172',
 '1722030',
 '173',
 '17342',
 '17385',
 '174',
 '1746918',
 '1749',
 '175',
 '1750',
 '175054701',
 '1754455243054000',
 '1755',
 '1757978',
 '1758',
 '176',
 '17611',
 '1767',
 '1769',
 '177',
 '1770',
 '1771',
 '17738',
 '1774',
 '1775',
 '177731',
 '1778',
 '178',
 '1781',
 '17817331',
 '17832',
 '178477',
 '1787',
 '1789',
 '179',
 '1791',
 '1793',
 '18',
 '180',
 '1800',
 '18002800',
 '1801',
 '1804',
 '181',
 '1819',
 '182',
 '1821286385673216',
 '1822',
 '1827',
 '1829',
 '183',
 '1831',
 ...]

In [16]:
# Lets transform the training data into a matrix
X_dtm = count_vect.transform(X)

In [17]:
# This new X returns a sparse matrix which we will convert into a dense matrix
X_dtm

<4993x50447 sparse matrix of type '<class 'numpy.int64'>'
	with 447953 stored elements in Compressed Sparse Row format>

In [18]:
# Converting a sparse matrix into a dense matrix
X_dtm.toarray()

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 4, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [19]:
# Lets form a dataframe using the dense matrix as rows, and the features of fitted vocabulary as columns
pd.DataFrame(X_dtm.toarray(),columns = count_vect.get_feature_names())

,00,000,0000,000000,000000000002858,000000000049773,000080,000099,0001,00018,...,zynve,zyqtaqlt,zyrtec,zyyqywp,zzezrjok,zzn,zzo,zzocb,zzso,zzsyt
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4988,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4990,0,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# We will use multinominal navie bayes model to create our model

In [20]:
# import and instantiate a Multinomial Naive Bayes model
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [61]:
len(X_dtm.toarray())

4993

In [62]:
len(y)

4993

In [21]:
# Lets train our model with original data, that is X and y
nb.fit(X_dtm,y)

MultinomialNB()

In [22]:
# Lets find out the prediction based on the actual in-sample data
y_pred = nb.predict(X_dtm)

In [23]:
# Lets calculate the prediction accuracy using accuracu_function, as it is a classification problem
from sklearn import metrics
print(metrics.accuracy_score(y,y_pred))

0.9901862607650711

The accuracy measured is 99 %, which is when the model is trained with data X, and y, and predictions were also made using X.

The accuracy measured in such a way is not a good estimator because, in the real life,this model will be faced with new data that it has not seen or been trained with. Thus, we will use train_test_split to split the X and y into training and testing sets respectively

# Using train_test_split

In [24]:
# split X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state = 0, test_size = 0.4)

In [25]:
print(X_train.shape)
print(X_test.shape)
print(y_test.shape)
print(y_train.shape)

(2995,)
(1998,)
(1998,)
(2995,)

In [26]:
print(type(X_test))

<class 'pandas.core.series.Series'>

In [27]:
# Lets instantiate the vectorizer
vect = CountVectorizer()

In [28]:
# Lets learn the vocabulary from X_train, and convert it into a sparse matrix
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)

# equivalently: combine fit and transform into a single step
            X_train_dtm = vect.fit_transform(X_train)

In [29]:
vect.get_feature_names()

['00',
 '000',
 '0000',
 '000000',
 '000000000002858',
 '000080',
 '000099',
 '0001',
 '00020608',
 '0004',
 '001',
 '001001',
 '0012',
 '001452',
 '002',
 '0022',
 '0025',
 '0027',
 '00298',
 '003',
 '0030',
 '003002',
 '0031',
 '0033',
 '0038',
 '004',
 '0044',
 '0047',
 '005',
 '00534580',
 '006',
 '006600',
 '0067',
 '007',
 '0071',
 '008',
 '009',
 '01',
 '010',
 '0100',
 '0101',
 '011',
 '0117',
 '012',
 '013',
 '0130',
 '014',
 '01405',
 '01408304990',
 '015',
 '016',
 '017',
 '0170',
 '01778',
 '019',
 '019017',
 '01915',
 '02',
 '020',
 '0200',
 '02010207',
 '021',
 '022',
 '0232',
 '025',
 '026',
 '027',
 '028',
 '02886',
 '02897893',
 '029',
 '03',
 '030',
 '0300',
 '03090806',
 '03149',
 '0325567',
 '033',
 '0331',
 '034',
 '0347',
 '035',
 '0357',
 '036',
 '0361770',
 '0363',
 '036474336',
 '037',
 '0373',
 '0375',
 '038',
 '0380',
 '039',
 '0393',
 '04',
 '040',
 '0400',
 '0401',
 '041',
 '0413',
 '043',
 '0435',
 '0439',
 '044',
 '045',
 '046',
 '04604902',
 '0469',
 '048',
 '049',
 '0491',
 '05',
 '050',
 '0500',
 '0505',
 '0506',
 '0507544',
 '052',
 '054',
 '055',
 '0569',
 '0570',
 '058',
 '059',
 '0598',
 '06',
 '0600',
 '061',
 '061300',
 '0614842809561657',
 '062',
 '062000',
 '0630',
 '065',
 '066',
 '067',
 '068',
 '0688',
 '069',
 '07',
 '070',
 '0700',
 '07080',
 '0713',
 '072',
 '073',
 '075',
 '076',
 '078',
 '08',
 '080',
 '0800',
 '081',
 '082',
 '0825',
 '083',
 '0839',
 '084',
 '085',
 '087',
 '088',
 '0880',
 '088889774',
 '089',
 '09',
 '0900',
 '09050804',
 '09110129',
 '0920',
 '093',
 '094',
 '0945',
 '095',
 '096',
 '0973',
 '0977',
 '098',
 '0980308',
 '0980391',
 '0980438',
 '0980439',
 '0980694',
 '0984126',
 '0984132',
 '0984136',
 '0984179',
 '0984229',
 '0984273',
 '0984284',
 '0984654',
 '0985192',
 '0986315',
 '0986363',
 '0986511',
 '0986563',
 '0986725',
 '0986757',
 '0986892',
 '0987283',
 '0988743',
 '0989703',
 '0989708',
 '0989709',
 '0989740',
 '0989751',
 '0989813',
 '0989842',
 '10',
 '100',
 '1000',
 '10000',
 '10010000873445724',
 '10010000876293700',
 '1002',
 '1005',
 '10077',
 '101',
 '10103',
 '101522',
 '101530',
 '1019',
 '101985',
 '102',
 '102056072',
 '1023',
 '102372',
 '1024',
 '102420',
 '1026',
 '102775',
 '103',
 '1031',
 '103745',
 '1038590',
 '1038591',
 '104',
 '1040',
 '104001',
 '104210',
 '104256',
 '104285',
 '1043',
 '104301',
 '104323',
 '104353',
 '104354',
 '104355',
 '1044',
 '104738',
 '104940',
 '104975',
 '105',
 '10500',
 '10502',
 '105124',
 '1052',
 '10545',
 '105629',
 '105630',
 '105631',
 '105632',
 '105633',
 '105634',
 '105638',
 '106',
 '1060',
 '1061',
 '1062',
 '106269',
 '106290',
 '106292',
 '1063',
 '106736',
 '107',
 '1072',
 '107937',
 '108',
 '1080',
 '108058',
 '108146',
 '108246',
 '1084',
 '108564',
 '108672',
 '1087',
 '109',
 '109046',
 '109475',
 '1095',
 '10955',
 '109670',
 '1098',
 '1099',
 '109925',
 '11',
 '110',
 '1100',
 '11000',
 '1102',
 '1103',
 '1104',
 '1105',
 '110502',
 '1106',
 '11079',
 '111',
 '112',
 '1123',
 '11230',
 '113',
 '1130',
 '1132',
 '113858',
 '114',
 '11400',
 '114096',
 '11417',
 '114427',
 '1145',
 '115',
 '11500',
 '1151',
 '1155',
 '1156',
 '1157',
 '116',
 '1160',
 '1164',
 '1165',
 '11669',
 '117',
 '1174',
 '117848',
 '1179',
 '118',
 '1180',
 '1181',
 '11814',
 '11864',
 '11871528',
 '1188',
 '1189',
 '119',
 '11958',
 '12',
 '120',
 '1200',
 '120000',
 '1201',
 '120266',
 '120359',
 '1207',
 '12079',
 '120866',
 '120891',
 '121',
 '1210',
 '1212',
 '122',
 '12200',
 '12214',
 '122218',
 '1225',
 '1226030',
 '123',
 '1233',
 '123395',
 '1237',
 '1239190',
 '124',
 '124400',
 '1248',
 '125',
 '1250',
 '125066',
 '1252',
 '1256',
 '125783',
 '125786',
 '125807',
 '125822',
 '125827',
 '125828',
 '125836',
 '125895',
 '125899',
 '125900',
 '126',
 '1260',
 '126281',
 '126289',
 '126336',
 '126358',
 '1265',
 '1266',
 '12667',
 '1269',
 '127',
 '127445',
 '1275',
 '12780',
 '12782',
 '127856',
 '128',
 '1280',
 '12831939',
 '128952',
 '129',
 '1290',
 '12930',
 '1294',
 '1295',
 '129706',
 '13',
 '130',
 '1300',
 '13000',
 '130913',
 '130917',
 '131',
 '131048',
 '131054',
 '1314',
 '1315',
 '131720',
 '131729',
 '132',
 '132030',
 '1326',
 '1328',
 '132832',
 '132975',
 '133',
 '133010',
 '133088',
 '133125',
 '133179',
 '133196',
 '1332',
 '133219',
 '133257',
 '133259',
 '1333',
 '133304',
 '133308',
 '1334',
 '133435',
 '1335',
 '1336',
 '134',
 '1343',
 '1344',
 '134755',
 '135',
 '1351',
 '1354',
 '135664',
 '135714',
 '135842',
 '135895',
 '135931652',
 '135958',
 '136',
 '1360',
 '136185',
 '136222',
 '136286',
 '136287',
 '136744',
 '136880',
 '136933',
 '137',
 '137156',
 '1372',
 '137205',
 '1373',
 '137595',
 '1376',
 '137858',
 '137870',
 '138',
 '138023',
 '138049',
 '138094',
 '138095',
 '1381',
 '138233',
 '138332',
 '1384',
 '138544',
 '138546',
 '138550',
 '138553',
 '138572',
 '1386',
 '138605',
 '138658',
 '138662',
 '138665',
 '139',
 '1390',
 '139057',
 '139058',
 '139067',
 '1391',
 '139363',
 '139397',
 '1394',
 '13964',
 '139661',
 '1399',
 '14',
 '140',
 '1400',
 '1401',
 '14031399',
 '140327',
 '140330',
 '140332',
 '140334',
 '140336',
 '140337',
 '14051',
 '14086',
 '1409',
 '141',
 '1411',
 '141186',
 '141691',
 '141977',
 '142',
 '142002',
 '142035',
 '142036',
 '142037',
 '14226',
 '142509',
 '1427',
 '1428',
 '1429',
 '143',
 '14300',
 '1431',
 '143558',
 '143559',
 '1436',
 '143673',
 '143709',
 '143885',
 '143887',
 '144',
 '144049',
 '144052',
 '1441',
 '1442',
 '144264',
 '144271',
 '1447',
 '144917',
 '144936',
 '145',
 '1450',
 '145075',
 '145125',
 '1454',
 '1458',
 '1459',
 '146',
 '1460',
 '1462',
 '1465',
 '146907159',
 '147',
 '147092',
 '1472',
 '1474',
 '148',
 '1481',
 '148376',
 '148381',
 '148382',
 '148386',
 '148388',
 '148390',
 '148391',
 '148396',
 '148415904',
 '1485',
 '1487',
 '1488',
 '14886',
 '149',
 '149421',
 '1495',
 '1497',
 '15',
 '150',
 '1500',
 '15000',
 '150325',
 '1505',
 '1506',
 '150642',
 '1508',
 '151',
 '1512',
 '151203',
 '1516',
 '151669',
 '151694',
 '1517',
 '152',
 '1520',
 '1521',
 '1524',
 '1525',
 '152638',
 '1528',
 '153',
 '1530',
 '1534',
 '154',
 '154608',
 '1549',
 '155',
 '1550',
 '155118',
 '1552',
 '1553',
 '1554',
 '1558',
 '156',
 '1560',
 '15600',
 '156071',
 '156247',
 '156258',
 '1563',
 '15631',
 '156337',
 '156342',
 '156383',
 '156387',
 '156657',
 '156658',
 '1567',
 '1568',
 '157',
 '157006',
 '157278',
 '157279',
 '157288',
 '157572',
 '1576',
 '158',
 '1581',
 '158220',
 '158625',
 '15880647714247442333',
 '159',
 '1591',
 '159194',
 '1595',
 '1596',
 '159640',
 '16',
 '160',
 '1600',
 '1601',
 '1603',
 '160579',
 '1606',
 '161',
 '16100',
 '161541',
 '1618',
 '162',
 '16231',
 '16259',
 '16275',
 '16276',
 '163',
 '163005',
 '16323',
 '16358',
 '1638',
 '163815',
 '163874',
 '164',
 '164003',
 '164172',
 '1646',
 '164669',
 '164708',
 '16488',
 '16495',
 '165',
 '165331',
 '165373',
 '1658245',
 '166',
 '166026',
 '166459',
 '166523',
 '1667',
 '166888',
 '166989',
 '167',
 '1671',
 '168',
 '1682426017',
 '16840862',
 '168454',
 '16884',
 '16888',
 '168884',
 '1689',
 '169',
 '169301',
 '1694',
 '17',
 '170',
 '1700',
 '170133',
 '1707',
 '17097613',
 '171',
 '172',
 '173',
 '17342',
 '174',
 '1746918',
 '175',
 '1750',
 '1755',
 '1757978',
 '176',
 '17611',
 '1767',
 '177',
 '1771',
 '17738',
 '177731',
 '1778',
 '178',
 '17817331',
 '178477',
 '1789',
 '179',
 '1791',
 '18',
 '180',
 '1800',
 '18002800',
 '1801',
 '1804',
 '181',
 '1819',
 '182',
 '1821286385673216',
 '1822',
 '1829',
 '183',
 '1831',
 '18313',
 '1836',
 '18372',
 '1839',
 '184',
 '1841',
 '1842',
 '1843',
 '1848',
 '185',
 '1851',
 '1856',
 '186',
 '1867',
 '1869',
 '18690',
 '187',
 '1876',
 '1877',
 '188',
 '1880',
 '1887',
 '189',
 '1893',
 '1895',
 '19',
 '190',
 '1907',
 '191',
 '1911',
 '1912',
 '1913',
 '1917',
 '192',
 '1921',
 '1927',
 '193',
 '1930',
 '1931',
 '1933',
 '1934',
 '1938',
 '194',
 '19436',
 '194543200',
 '1947',
 '195',
 '1950',
 '19500',
 '1954',
 '1957',
 '1958',
 '1960',
 '1963',
 '1968',
 '1970',
 '1977',
 '1978',
 '19785',
 '1979',
 '198',
 '1980',
 '19803',
 '1981',
 '1982',
 '1983',
 '1987',
 '1988',
 '1989',
 '199',
 '1990',
 '1991',
 '1992',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '20',
 '200',
 '2000',
 '20000',
 '200007',
 '2001',
 '20014804',
 '20014903',
 '2002',
 '2003',
 '20032',
 '2003451',
 '20037',
 '2004',
 '20040929124340',
 '200412152150',
 '20046',
 '2005',
 '200502141853',
 '20055',
 '2006',
 '20089',
 '20093',
 '201',
 '20108',
 '201470',
 '2015',
 '201636',
 '201810',
 '201839',
 '20187',
 '20189',
 '2019',
 '20191',
 '201952',
 '202',
 '202672',
 '2027',
 '203',
 '203354',
 '204',
 '2047',
 '204777',
 '205',
 '205533',
 '205569',
 '206',
 '20606100',
 '2063',
 '206964994',
 '207',
 '2073256',
 '208',
 '2080774744588021497',
 '208083',
 '208092534',
 '208101',
 '209',
 '209015',
 '2098073',
 '2099764',
 '21',
 '210',
 '2100',
 '21071400',
 '210722',
 '211',
 '211573',
 '2118',
 '21195',
 '212',
 '212225',
 '213',
 '213005',
 '213145',
 '213370',
 '214',
 '21424229',
 '2144',
 '2145',
 '214948',
 '215',
 '21500',
 '216',
 '2165456',
 '216574588',
 '21667',
 '217',
 '2171',
 '218',
 '219',
 '2195',
 '21964',
 '219685',
 '22',
 '220',
 '220339',
 '2207',
 '221',
 '222',
 '2220',
 '222051',
 '222215',
 '223',
 '2234',
 '223423',
 '223458',
 '224',
 '22400',
 '225',
 '22507436373',
 '2256',
 '22592000',
 '226',
 '22600',
 '226138',
 '226538',
 '226611',
 '226713',
 '226763',
 '227',
 '22700',
 '227229',
 '227463',
 '2275',
 '227727',
 '228',
 '2283',
 '228568242',
 '229',
 '2293',
 '2294',
 '229481',
 '229490',
 '229501',
 '229532',
 '229535',
 '229541',
 '229575',
 '229586',
 '229609',
 '229758',
 '229857',
 '23',
 '230',
 '2300',
 '231',
 '231757',
 '231758',
 '232',
 '2328',
 '233',
 '233763',
 '2339077915',
 '234',
 '2341930101',
 '23447',
 '2345',
 ...]

In [30]:
# Lets convert X_dtm, which is a document term matrix or a sparse matrix, into a dense matrix
X_train_dtm = X_train_dtm.toarray()

In [31]:
# Lets print our new dense matrix, which is overrided into the previous sparse matrix 'X_dtm'
print(X_train_dtm)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 2 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

In [32]:
# Lets form a dataframe using the dense matrix as rows, and the features of fitted vocabulary as columns
pd.DataFrame(X_train_dtm, columns=vect.get_feature_names())

,00,000,0000,000000,000000000002858,000080,000099,0001,00020608,0004,...,zyban,zyjvit,zykfe,zynve,zyqtaqlt,zyrtec,zyyqywp,zzn,zzo,zzsyt
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2991,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2993,0,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Time to transform the X_test into a document term matrix

In [33]:
# transform testing data (using fitted vocabulary) into a document-term matrix
X_test_dtm = vect.transform(X_test)

In [34]:
# Lets instantiate a Multinomial Naive Bayes model
nb = MultinomialNB()

In [35]:
nb.fit(X_train_dtm,y_train)

MultinomialNB()

In [36]:
# Lets make prediction using a testing data that is: X_test
y_pred_new = nb.predict(X_test_dtm)

# Lets calculate the accuracy now
metrics.accuracy_score(y_test, y_pred_new)

0.9719719719719719

In [37]:
# Lets make a out of sample prediction for this updated model
spam_message = ['Hello sujan, you have won $50. Please send me your credit card number and confirmation code to confirm the prize']

# Lets transform the spam message into a sparse matrix
spam_message_dtm = vect.transform(spam_message)

In [65]:
spam_message_dtm

<1x37062 sparse matrix of type '<class 'numpy.int64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [39]:
#spam_message_dtm = pd.DataFrame(spam_message_dtm.toarray(), columns=vect.get_feature_names())

In [66]:
nb.predict(spam_message_dtm)

array([1], dtype=int64)

 array([1]) means the message "spam_message_dtm" is a spam message

# Lets try another testing spam message

In [41]:
# This email is predicted to be spam
spam_message2= ['Congratulations. You have won 100 pounds. Please go to this email address to confirm the prize. And, also send us your social security number']
nb.predict(vect.transform(spam_message2))

array([1], dtype=int64)

In [56]:
lis = ['Ham','Spam']

message = 'Sulav has won $ 10000. Please buy this product for $ 300. You can access the product form this link: http://ww.ssp.sp'
result = int(nb.predict(vect.transform([message])))
print(lis[result])

Spam

# Lets try a non-spam or ham message

In [42]:
# This email is predicted to be non-spam or ham
ham_message = ['Congratulations sujan for winning $300000. Lets party on the coming weekends on vegas. What do you say?']
nb.predict(vect.transform(ham_message))

array([0], dtype=int64)

In [43]:
message = '''
        Dear Students,

        We hope you and your family are doing well and keeping safe!

        We are delighted to inform you about the internship opportunity at the ING call center. Kindly send us your cv before 10 AM tomorrow (Sunday, 12 Sept. 2021)  if you are interested in the internship opportunity. 

        Please find the job description attached along with this email for your reference.

        Thanks and regards. '''
nb.predict(vect.transform([message]))

array([0], dtype=int64)

Since this is a binary classification problem, there exist the possibility of false positives, false negatives, True positives and True negatives. So, lets form our confuision matrix to find such cases.

In [44]:
# Lets create our confusion matrix
cm = metrics.confusion_matrix(y_test, y_pred_new)
cm

array([[1412,   20],
       [  36,  530]], dtype=int64)

In [45]:
# save confusion matrix and slice into 4 pieces 
TP = cm[1,1]
TN = cm[0,0]
FP = cm[0,1]
FN = cm[1,0]

In the confusion matrix above, It is presented as: [[TN,FP],[FN,TP]], where:

        TN = True Positive
        FP = False Positive
        FN = False Negative
        TP = True Positive

In [46]:
# Here, using the confusion matrix, accuracy can be measured as ((FP+FN)/ (TP+TN+FP+FN))
print("The overall accuracy is: ", (TP+TN)/ float(TP+TN+FP+FN))

The overall accuracy is:  0.9719719719719719

# Thank you - By Sujan Neupane